const mobs =[
{
	alive:true,
	name:'Mouse',
	level :0,
	HP:30,
	AtkPwr:50,
	XP:30,
	gif:'http://media0.giphy.com/media/EPwELUbhreEPC/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Bodyslam from a bunny',
	level :0,
	HP:60,
	AtkPwr:50,
	XP:30,
	gif:'http://media0.giphy.com/media/871qwDxfSemEE/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Male K-pop star',
	level :2,
	HP:60,
	AtkPwr:12,
	XP:20,
	gif:'http://media4.giphy.com/media/I68L0Ls9aH8di/giphy-downsized.gif',
	deathText:'',
},

{
	alive:true,
	name:'Very sticky lollipop',
	level :2,
	HP:75,
	AtkPwr:5,
	XP:15,
	gif:'http://media4.giphy.com/media/ilziDg6kdEOvC/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Sexually aggresive Penguine',
	level :4,
	HP:50,
	AtkPwr:40,
	XP:40,
	gif:'http://media2.giphy.com/media/xbyP5zWsmMsda/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Inconvinient Tomato',
	level :5,
	HP:400,
	AtkPwr:2,
	XP:7,
	gif:'http://media4.giphy.com/media/u0RJpGkLO0X7y/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'KilleSlipper McChoker',
	level :10,
	HP:100,
	AtkPwr:70,
	XP:70,
	gif: 'http://media3.giphy.com/media/KijmmcKP62qWs/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Under Duvercover Agent',
	level :10,
	HP:150,
	AtkPwr:80,
	XP:70,
	gif:'http://media3.giphy.com/media/c5yFdzgsIHzoY/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Tent Trap!',
	level :10,
	HP:80,
	AtkPwr:175,
	XP:70,
	gif:'http://media3.giphy.com/media/lyjDRCftAkFaM/giphy.gif',
	deathText:'',
},
{
	alive:true,
	name:'Young Korean Teakondo Prodegies',
	level :10,
	HP:300,
	AtkPwr:150,
	XP:70,
	gif:'http://media1.giphy.com/media/gGy34VQFk9mOQ/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Young Korean Teakondo Prodegies',
	level :10,
	HP:380,
	AtkPwr:100,
	XP:70,
	gif:'http://media1.giphy.com/media/MZzMRR6JfIiME/giphy.gif',
	deathText:'',
},
{
	alive:true,
	name:'AWSOME POWER OF NATURE!',
	level :10,
	HP:900,
	AtkPwr:30,
	XP:70,
	gif:'http://media4.giphy.com/media/U0GqVamOu9NPa/giphy.gif',
	deathText:'',
},
{
	alive:true,
	name:'Cool kid on the block',
	level :10,
	HP:400,
	AtkPwr:100,
	XP:50,
	gif:'http://media1.giphy.com/media/KXY5lB8yOarLy/giphy-downsized.gif',
	deathText:'',
},

{
	alive:true,
	name:'dangerous Science contraption',
	level :15,
	HP:1000,
	AtkPwr:100,
	XP:70,
	gif:'https://media.giphy.com/media/h6SiBm6SBa4da/giphy.gif',
	deathText:'',
},
{
	alive:true,
	name:'Dangerous supprise attack',
	level :15,
	HP:80,
	AtkPwr:100,
	XP:70,
	gif:'http://media0.giphy.com/media/jkpVaBMVt0ZfW/giphy.gif',
	deathText:'',
},
{
	alive:true,
	name:'Lonely Nerd',
	level :15,
	HP:250,
	AtkPwr:40,
	XP:70,
	gif:'http://media1.giphy.com/media/VfyC5j7sR4cso/giphy.gif',
	deathText:'',
},
{
	alive:true,
	name:'Herd of killer ducks',
	level :15,
	HP:400,
	AtkPwr:100,
	XP:40,
	gif:'http://media2.giphy.com/media/5ZG4uADPJNZPa/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'That old nice lady',
	level :15,
	HP:800,
	AtkPwr:40,
	XP:40,
	gif:'http://media0.giphy.com/media/9IVTJHx7l8HPa/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Rejected look for Elmo',
	level :15,
	HP:500,
	AtkPwr:150,
	XP:40,
	gif:'http://media.giphy.com/media/3o72EVdWZ6oGV9mi1W/giphy-tumblr.gif',
	deathText:'',
},
{
	alive:true,
	name:'Your lonely ex at X-mas',
	level :15,
	HP:500,
	AtkPwr:150,
	XP:40,
	gif:'',
	deathText:'http://media1.giphy.com/media/xUySTx78TRW7uvu7g4/giphy-tumblr.gif',
},




]

