const mobs =[
{
	alive:true,
	name:'mouse',
	level :0,
	HP:30,
	AtkPwr:50,
	XP:30,
	gif:'http://media0.giphy.com/media/EPwELUbhreEPC/giphy-downsized.gif',
	deathText:'',
},
// {
// 	alive:true,
// 	name:'',
// 	level :15,
// 	HP:60,
// 	AtkPwr:40,
// 	XP:30,
// 	gif:'https://media0.giphy.com/media/oiGCnybFPh6Q8/200_s.gif',
// 	deathText:'',
// },
// {
// 	alive:true,
// 	name:'Poison death flower',
// 	level :1,
// 	HP:20,
// 	AtkPwr:200,
// 	XP:30,
// 	gif:'http://i.imgur.com/CZUl23l.gifv',
// 	deathText:'',
// },
{
	alive:true,
	name:'Male K-pop star',
	level :2,
	HP:60,
	AtkPwr:12,
	XP:20,
	gif:'http://media4.giphy.com/media/I68L0Ls9aH8di/giphy-downsized.gif',
	deathText:'',
},

{
	alive:true,
	name:'Very sticky lollipop',
	level :2,
	HP:75,
	AtkPwr:5,
	XP:15,
	gif:'http://media4.giphy.com/media/ilziDg6kdEOvC/giphy-downsized.gif',
	deathText:'',
},


{
	alive:true,
	name:'Sexually aggresive Penguine',
	level :4,
	HP:50,
	AtkPwr:40,
	XP:40,
	gif:'http://media2.giphy.com/media/xbyP5zWsmMsda/giphy-downsized.gif',
	deathText:'',
},

{
	alive:true,
	name:'Inconvinient Tomato',
	level :5,
	HP:400,
	AtkPwr:2,
	XP:10,
	gif:'http://media4.giphy.com/media/u0RJpGkLO0X7y/giphy-downsized.gif',
	deathText:'',
},

{
	alive:true,
	name:'KilleSlipper McChoker',
	level :10,
	HP:100,
	AtkPwr:70,
	XP:70,
	gif: 'http://media3.giphy.com/media/KijmmcKP62qWs/giphy-downsized.gif',
	deathText:'',
},

{
	alive:true,
	name:'Under Duvercover Agent',
	level :10,
	HP:60,
	AtkPwr:10,
	XP:70,
	gif:'http://media3.giphy.com/media/c5yFdzgsIHzoY/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'Young Korean Teakondo Prodegies',
	level :10,
	HP:1000,
	AtkPwr:80,
	XP:70,
	gif:'http://media1.giphy.com/media/gGy34VQFk9mOQ/giphy-downsized.gif',
	deathText:'',
},
{
	alive:true,
	name:'dangerous Science contraption',
	level :15,
	HP:1000,
	AtkPwr:100,
	XP:70,
	gif:'https://media.giphy.com/media/h6SiBm6SBa4da/giphy.gif',
	deathText:'',
},
{
	alive:true,
	name:'Dangerous supprise attack',
	level :15,
	HP:80,
	AtkPwr:100,
	XP:70,
	gif:'http://media0.giphy.com/media/jkpVaBMVt0ZfW/giphy.gif',
	deathText:'',
},


]

